FROM postgres:17.4

ENV POSTGRES_DB=localdb
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=adminPassword
ENV TZ=ASIA/SEOUL

EXPOSE 5432

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1
